### ISSUE TITLE
gcc linker files missing

### ISSUE THREAD

**Issue by stefaneicher** [STMicroelectronics/cmsis_device_l0#3]
Hi can you also add the gcc linker files?
https://github.com/STMicroelectronics/cmsis_device_l0/tree/master/Source/Templates/gcc

**Comment by TOUNSTM** [comment]
Hello @stefaneicher 
As  @RKOUSTM said in this issue [#7](https://github.com/STMicroelectronics/STM32CubeL1/issues/7) we don't provide  GCC linker files  to legacy products.
Please, allow me to close this issue. Thank you for your comprehension.
With Regards,
